// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZOMlWSGlFIxXzIZMosw1JYzSuE1WONKI',
    appId: '1:531306922897:android:f34d03fd6f6689e38e1030',
    messagingSenderId: '531306922897',
    projectId: 'inr-takip-app',
    storageBucket: 'inr-takip-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPFpC0e0Kv6elyYczGFRyn6uqUGccVWHI',
    appId: '1:531306922897:ios:addc035de297b64c8e1030',
    messagingSenderId: '531306922897',
    projectId: 'inr-takip-app',
    storageBucket: 'inr-takip-app.firebasestorage.app',
    iosBundleId: 'com.mirketteknoloji.inrtakip',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc_MUdk53Icqq9rpHvKQenjDMk1pPshcw',
    appId: '1:531306922897:web:c5c470b4ea04f5dc8e1030',
    messagingSenderId: '531306922897',
    projectId: 'inr-takip-app',
    authDomain: 'inr-takip-app.firebaseapp.com',
    storageBucket: 'inr-takip-app.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPFpC0e0Kv6elyYczGFRyn6uqUGccVWHI',
    appId: '1:531306922897:ios:2900730aa8c207678e1030',
    messagingSenderId: '531306922897',
    projectId: 'inr-takip-app',
    storageBucket: 'inr-takip-app.firebasestorage.app',
    iosBundleId: 'com.example.inrTakip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc_MUdk53Icqq9rpHvKQenjDMk1pPshcw',
    appId: '1:531306922897:web:35c88589fc1e06de8e1030',
    messagingSenderId: '531306922897',
    projectId: 'inr-takip-app',
    authDomain: 'inr-takip-app.firebaseapp.com',
    storageBucket: 'inr-takip-app.firebasestorage.app',
  );

}